import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Hackathone - Figma - Template 9",
  description: "Generated by hammad hafeez",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
